# Generated by Django 5.1.3 on 2024-12-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentRegisteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(max_length=30)),
                ('password_confirmation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StaffRegisteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(max_length=30)),
                ('password_confirmation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegisteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(max_length=30)),
                ('password_confirmation', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
