# Generated by Django 5.1.3 on 2024-12-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_parentregisteration_staffregisteration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentregisteration',
            name='phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffregisteration',
            name='phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentregisteration',
            name='phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
