# Generated by Django 5.1.3 on 2024-12-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_parentregisteration_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentregisteration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='staffregisteration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='studentregisteration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
