# Generated by Django 5.1.4 on 2024-12-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_parentregisteration_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentregisteration',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='parentregisteration',
            name='password_confirmation',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='staffregisteration',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='staffregisteration',
            name='password_confirmation',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='studentregisteration',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='studentregisteration',
            name='password_confirmation',
            field=models.CharField(max_length=128),
        ),
    ]
