# Generated by Django 5.1.4 on 2024-12-15 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_parentregisteration_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentregisteration',
            name='password_confirmation',
        ),
        migrations.RemoveField(
            model_name='staffregisteration',
            name='password_confirmation',
        ),
        migrations.RemoveField(
            model_name='studentregisteration',
            name='password_confirmation',
        ),
    ]
