# Generated by Django 5.1.3 on 2024-12-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondarySchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_school_name', models.CharField(max_length=30)),
                ('secondary_school_email', models.EmailField(max_length=254)),
                ('secondary_school_eircode', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
