# Generated by Django 5.1.3 on 2024-12-09 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0004_secondaryschool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secondary_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_student_name', models.CharField(max_length=30)),
                ('secondary_class_year', models.CharField(max_length=30)),
                ('secondary_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='admin_section.secondaryschool')),
            ],
        ),
    ]
