# Generated by Django 5.1.3 on 2024-12-09 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0005_secondary_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Secondary_Student',
            new_name='SecondaryStudent',
        ),
    ]
