# Generated by Django 5.1.3 on 2024-12-09 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0006_rename_secondary_student_secondarystudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='admin_section.teacher'),
            preserve_default=False,
        ),
    ]
