# Generated by Django 5.1.4 on 2024-12-12 17:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0009_categories_menuitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('menu_day', models.CharField(blank=True, max_length=100, null=True)),
                ('menu_date', models.DateField(default=datetime.datetime.today)),
                ('cycle_name', models.CharField(max_length=100)),
                ('is_active_time', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='admin_section.categories')),
                ('primary_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='admin_section.primaryschool')),
                ('secondary_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='admin_section.secondaryschool')),
            ],
        ),
    ]
