# Generated by Django 4.2.9 on 2024-12-12 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0011_alter_menu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='primary_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='admin_section.primaryschool'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='secondary_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='admin_section.secondaryschool'),
        ),
    ]
