# Generated by Django 4.2.9 on 2024-12-13 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0012_alter_menu_primary_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='is_active_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
