# Generated by Django 4.2.9 on 2024-12-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0013_alter_menu_is_active_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='is_active_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
