# Generated by Django 4.2.9 on 2024-12-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0014_alter_menu_is_active_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
