# Generated by Django 5.1.4 on 2024-12-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0016_menu_end_date_menu_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondarystudent',
            name='seconadry_student_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
