# Generated by Django 5.1.4 on 2024-12-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0017_secondarystudent_seconadry_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='end_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
