# Generated by Django 5.1.4 on 2024-12-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0018_alter_menu_end_date_alter_menu_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='nutrient_quantity',
            field=models.IntegerField(max_length=255),
        ),
    ]
