# Generated by Django 5.1.4 on 2024-12-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0019_alter_menuitems_nutrient_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='nutrient_quantity',
            field=models.IntegerField(),
        ),
    ]
