# Generated by Django 5.1.4 on 2024-12-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0023_remove_order_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryschool',
            name='school_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='secondaryschool',
            name='secondary_school_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
