# Generated by Django 5.1.4 on 2024-12-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0025_menuitems_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitems',
            name='nutrient_name',
        ),
        migrations.RemoveField(
            model_name='menuitems',
            name='nutrient_quantity',
        ),
        migrations.AddField(
            model_name='menuitems',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='nutrients',
            field=models.JSONField(default=list),
        ),
    ]
