# Generated by Django 5.1.4 on 2024-12-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0032_alter_order_week_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
