# Generated by Django 5.1.4 on 2024-12-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0034_order_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='fk_menu_item_id',
            new_name='menu',
        ),
    ]
