# Generated by Django 5.1.4 on 2024-12-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0036_alter_menu_cycle_name_alter_orderitem_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='cycle_name',
            field=models.CharField(max_length=100),
        ),
    ]
