# Generated by Django 5.1.4 on 2024-12-20 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0037_alter_menu_cycle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteenstaff',
            name='primary_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_section.primaryschool'),
        ),
        migrations.AddField(
            model_name='canteenstaff',
            name='school_type',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='canteenstaff',
            name='secondary_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_section.secondaryschool'),
        ),
    ]
