# Generated by Django 5.1.4 on 2024-12-21 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0038_canteenstaff_primary_school_canteenstaff_school_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=30)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_section.studentregisteration')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_section.staffregisteration')),
            ],
        ),
    ]
