# Generated by Django 5.1.4 on 2024-12-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0040_remove_class_student_remove_class_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentregisteration',
            name='allergies',
            field=models.ManyToManyField(blank=True, null=True, to='admin_section.allergen'),
        ),
        migrations.AddField(
            model_name='primarystudent',
            name='allergies',
            field=models.ManyToManyField(blank=True, null=True, to='admin_section.allergen'),
        ),
        migrations.AddField(
            model_name='staffregisteration',
            name='allergies',
            field=models.ManyToManyField(blank=True, null=True, to='admin_section.allergen'),
        ),
        migrations.AlterField(
            model_name='allergen',
            name='allergy',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='menuitems',
            name='allergies',
        ),
        migrations.AddField(
            model_name='menuitems',
            name='allergies',
            field=models.ManyToManyField(blank=True, null=True, to='admin_section.allergen'),
        ),
    ]
