# Generated by Django 5.1.4 on 2024-12-22 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0041_parentregisteration_allergies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitems',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='parentregisteration',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='primarystudent',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='staffregisteration',
            name='allergies',
        ),
        migrations.AddField(
            model_name='menuitems',
            name='allergies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_section.allergen'),
        ),
        migrations.AddField(
            model_name='parentregisteration',
            name='allergies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_section.allergen'),
        ),
        migrations.AddField(
            model_name='primarystudent',
            name='allergies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_section.allergen'),
        ),
        migrations.AddField(
            model_name='staffregisteration',
            name='allergies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_section.allergen'),
        ),
    ]
