# Generated by Django 5.1.4 on 2024-12-22 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0042_remove_menuitems_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarystudent',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_parent', to='admin_section.parentregisteration'),
        ),
        migrations.AlterField(
            model_name='primarystudent',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='admin_section.primaryschool'),
        ),
        migrations.AlterField(
            model_name='primarystudent',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_staff', to='admin_section.staffregisteration'),
        ),
        migrations.AlterField(
            model_name='primarystudent',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_teacher', to='admin_section.teacher'),
        ),
    ]
