# Generated by Django 5.1.4 on 2024-12-22 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0044_alter_primarystudent_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarystudent',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_staff', to='admin_section.staffregisteration'),
        ),
    ]
