# Generated by Django 5.1.4 on 2024-12-22 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0046_alter_primarystudent_school_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='primarystudent',
            old_name='student_email',
            new_name='email',
        ),
    ]
