# Generated by Django 5.1.4 on 2024-12-22 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0048_remove_parentregisteration_allergies_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allergen',
            new_name='Allergens',
        ),
    ]
