# Generated by Django 5.1.4 on 2024-12-22 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0049_rename_allergen_allergens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='allergies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuitems', to='admin_section.allergens'),
        ),
    ]
