# Generated by Django 5.1.4 on 2024-12-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0050_alter_menuitems_allergies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitems',
            name='allergies',
        ),
        migrations.AddField(
            model_name='menuitems',
            name='allergies',
            field=models.ManyToManyField(blank=True, null=True, related_name='menuitems', to='admin_section.allergens'),
        ),
    ]
