# Generated by Django 5.1.4 on 2024-12-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0051_remove_menuitems_allergies_menuitems_allergies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentregisteration',
            name='allergies',
            field=models.ManyToManyField(blank=True, null=True, to='admin_section.allergens'),
        ),
        migrations.RemoveField(
            model_name='primarystudent',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='staffregisteration',
            name='allergies',
        ),
        migrations.AddField(
            model_name='primarystudent',
            name='allergies',
            field=models.ManyToManyField(blank=True, null=True, to='admin_section.allergens'),
        ),
        migrations.AddField(
            model_name='staffregisteration',
            name='allergies',
            field=models.ManyToManyField(blank=True, null=True, to='admin_section.allergens'),
        ),
    ]
