# Generated by Django 5.1.4 on 2024-12-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0053_remove_primarystudent_allergies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primarystudent',
            name='allergies',
        ),
        migrations.AddField(
            model_name='primarystudent',
            name='allergies',
            field=models.ManyToManyField(blank=True, null=True, to='admin_section.allergens'),
        ),
    ]
