# Generated by Django 5.1.4 on 2024-12-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0054_remove_primarystudent_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
