# Generated by Django 5.1.4 on 2024-12-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0056_alter_order_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondaryschool',
            name='school_type',
            field=models.CharField(blank=True, choices=[('secondary', 'Secondary'), ('primary', 'Primary')], max_length=30, null=True),
        ),
    ]
