# Generated by Django 5.1.4 on 2024-12-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0058_remove_secondaryschool_school_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='is_active_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
