# Generated by Django 5.1.4 on 2024-12-30 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0060_staffregisteration_primary_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='primary_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_student', to='admin_section.primarystudentsregister'),
        ),
        migrations.AddField(
            model_name='order',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='admin_section.staffregisteration'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='orders', through='admin_section.OrderItem', to='admin_section.menu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='admin_section.secondarystudent'),
        ),
    ]
