# Generated by Django 5.1.4 on 2025-01-06 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0066_parentregisteration_credits_secondarystudent_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuitem', to='admin_section.menu'),
        ),
    ]
