# Generated by Django 5.1.4 on 2025-01-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0067_alter_orderitem_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentregisteration',
            name='credits',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='secondarystudent',
            name='credits',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='staffregisteration',
            name='credits',
            field=models.FloatField(default=0.0),
        ),
    ]
