# Generated by Django 5.1.4 on 2025-01-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0069_primarystudentsregister_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
