# Generated by Django 5.1.4 on 2025-01-15 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0070_order_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_id',
            new_name='payment_method_id',
        ),
    ]
