# Generated by Django 5.1.4 on 2025-01-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0071_rename_payment_id_order_payment_method_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method_id',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
