# Generated by Django 5.1.4 on 2025-02-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0072_remove_order_payment_method_id_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='is_active_time',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='start_date',
        ),
        migrations.AddField(
            model_name='menu',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
