# Generated by Django 5.1.4 on 2025-03-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0073_remove_menu_end_date_remove_menu_is_active_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/'),
        ),
    ]
