# Generated by Django 5.1.4 on 2025-04-14 20:09

import admin_section.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0075_unverifieduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='unverifieduser',
            name='expiry_time',
            field=models.DateTimeField(default=admin_section.models.get_expiry_time),
        ),
        migrations.AlterField(
            model_name='unverifieduser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='unverifieduser',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
