# Generated by Django 5.1.4 on 2025-06-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0076_unverifieduser_expiry_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unverifieduser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
