# Generated by Django 5.1.4 on 2025-06-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0077_unverifieduser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='unverifieduser',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('facebook', 'Facebook'), ('microsoft', 'Microsoft')], default='email', max_length=20),
        ),
    ]
