# Generated by Django 5.1.4 on 2025-08-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0078_unverifieduser_login_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='child_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='week_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='year',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='parentregisteration',
            name='phone_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='secondarystudent',
            name='phone_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffregisteration',
            name='phone_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
