# Generated by Django 5.1.4 on 2025-08-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0080_alter_contactmessage_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='primary_school',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='secondary_school',
        ),
        migrations.AddField(
            model_name='menu',
            name='primary_schools',
            field=models.ManyToManyField(blank=True, related_name='menus', to='admin_section.primaryschool'),
        ),
        migrations.AddField(
            model_name='menu',
            name='secondary_schools',
            field=models.ManyToManyField(blank=True, related_name='menus', to='admin_section.secondaryschool'),
        ),
    ]
