# Generated by Django 5.1.4 on 2025-08-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0082_parentregisteration_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10)),
                ('latest_version', models.CharField(max_length=20)),
                ('min_supported_version', models.CharField(default='1.0.0', max_length=20)),
                ('force_update', models.BooleanField(default=False)),
            ],
        ),
    ]
