# Generated by Django 5.1.4 on 2025-09-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0084_order_created_at_parentregisteration_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primarystudentsregister',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='unverifieduser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
