# Generated by Django 5.1.4 on 2025-09-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0085_remove_primarystudentsregister_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentregisteration',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='secondarystudent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='staffregisteration',
            name='created_at',
        ),
    ]
