# Generated by Django 5.1.4 on 2025-09-09 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0086_remove_parentregisteration_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
    ]
