# Generated by Django 5.1.4 on 2025-09-09 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0088_remove_order_items_name_alter_order_primary_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='primary_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_student', to='admin_section.primarystudentsregister'),
        ),
        migrations.AlterField(
            model_name='order',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='admin_section.staffregisteration'),
        ),
        migrations.AlterField(
            model_name='order',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='admin_section.secondarystudent'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items_menu', to='admin_section.menu'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='admin_section.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.BigIntegerField(),
        ),
    ]
