# Generated by Django 5.1.4 on 2025-09-09 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0090_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='menuitems', to='admin_section.allergens'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items_menu', to='admin_section.menu'),
        ),
        migrations.AlterField(
            model_name='parentregisteration',
            name='allergies',
            field=models.ManyToManyField(blank=True, to='admin_section.allergens'),
        ),
        migrations.AlterField(
            model_name='primarystudentsregister',
            name='allergies',
            field=models.ManyToManyField(blank=True, to='admin_section.allergens'),
        ),
        migrations.AlterField(
            model_name='secondarystudent',
            name='allergies',
            field=models.ManyToManyField(blank=True, to='admin_section.allergens'),
        ),
        migrations.AlterField(
            model_name='staffregisteration',
            name='allergies',
            field=models.ManyToManyField(blank=True, to='admin_section.allergens'),
        ),
    ]
