# Generated by Django 5.1.4 on 2025-10-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0093_worker_alter_canteenstaff_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='confirm_password',
        ),
    ]
