# Generated by Django 5.1.4 on 2025-10-20 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0094_remove_manager_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='confirm_password',
        ),
    ]
