# Generated by Django 5.1.4 on 2025-10-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0095_remove_worker_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='production_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
