# Generated by Django 5.1.4 on 2025-10-27 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0096_menuitems_is_available_menuitems_production_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('week_number', models.PositiveIntegerField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('selected_day', models.CharField(blank=True, max_length=20, null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='admin_section.manager')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('production_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_order_items', to='admin_section.menuitems')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='admin_section.managerorder')),
            ],
        ),
    ]
