# Generated by Django 5.1.4 on 2025-10-27 09:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0097_managerorder_managerorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='managerorder',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
