# Generated by Django 5.1.4 on 2025-10-27 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0099_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerorder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
    ]
