# Generated by Django 5.1.4 on 2025-10-29 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0101_document_workerdocumentstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='created_by',
        ),
    ]
