# Generated by Django 5.2.8 on 2025-12-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0103_order_created_at_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentregisteration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='secondarystudent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='staffregisteration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
