# Generated by Django 5.2.8 on 2025-12-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0104_parentregisteration_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentregisteration',
            name='android_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parentregisteration',
            name='ios_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='secondarystudent',
            name='android_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='secondarystudent',
            name='ios_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staffregisteration',
            name='android_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staffregisteration',
            name='ios_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
