# Generated by Django 5.2.8 on 2026-01-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0105_parentregisteration_android_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentregisteration',
            name='platform_type',
            field=models.CharField(blank=True, choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='primarystudentsregister',
            name='android_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='primarystudentsregister',
            name='ios_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='primarystudentsregister',
            name='platform_type',
            field=models.CharField(blank=True, choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='secondarystudent',
            name='platform_type',
            field=models.CharField(blank=True, choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='staffregisteration',
            name='platform_type',
            field=models.CharField(blank=True, choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=10, null=True),
        ),
    ]
