# Generated by Django 5.2.8 on 2026-03-08 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0107_alter_document_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('spending_threshold', models.DecimalField(decimal_places=2, help_text='Minimum total spending required to qualify', max_digits=10)),
                ('credit_reward', models.DecimalField(decimal_places=2, help_text='Credits to award when conditions are met', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_type', models.CharField(choices=[('parent', 'Parent'), ('staff', 'Staff'), ('student', 'Student')], max_length=20)),
                ('credited_at', models.DateTimeField(auto_now_add=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_promotions', to='admin_section.promotion')),
            ],
            options={
                'unique_together': {('promotion', 'user_id', 'user_type')},
            },
        ),
    ]
