# Generated by Django 5.2.8 on 2026-03-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0108_promotion_userpromotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='exclude_primary_orders',
            field=models.BooleanField(default=False, help_text='Exclude primary school (free) orders from spending and count checks'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='max_redemptions',
            field=models.PositiveIntegerField(blank=True, help_text='Max total redemptions across all users. Null = unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='min_order_count',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum number of orders user must have placed', null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='schools',
            field=models.JSONField(blank=True, default=list, help_text='Schools this promotion applies to. Empty = all schools.'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='credit_reward',
            field=models.DecimalField(decimal_places=2, help_text='Credits to award when all conditions are met', max_digits=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='spending_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum total spending required', max_digits=10, null=True),
        ),
    ]
