# Generated by Django 5.2.8 on 2026-03-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0109_promotion_add_condition_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='primary_school',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='school_type',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='secondary_school',
        ),
        migrations.AddField(
            model_name='managerorder',
            name='manager_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='managerorder',
            name='school_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerorder',
            name='school_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
